# Generated by Django 5.2.4 on 2025-10-09 14:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AltseasonReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_altseason', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='AverageRsiReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('avg_rsi', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_ts', models.DateTimeField(blank=True, null=True)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=30)),
                ('market_cap_pct_24h', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('vol_24h', models.DecimalField(decimal_places=2, max_digits=30)),
                ('vol_24h_pct_24h', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('active_cryptos', models.IntegerField(blank=True, null=True)),
                ('active_exchanges', models.IntegerField(blank=True, null=True)),
                ('active_market_pairs', models.IntegerField(blank=True, null=True)),
                ('btc_dominance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('eth_dominance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Top20IndexPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('index_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('pct_change_24h', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='FearGreedReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveSmallIntegerField()),
                ('classification', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['-ts'],
                'unique_together': {('ts', 'value')},
            },
        ),
    ]
