# Generated by Django 5.2.4 on 2025-08-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('post_image', models.ImageField(upload_to='post_images/', verbose_name='Post Image')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=10, verbose_name='Status')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('read_time', models.PositiveIntegerField(blank=True, help_text='Minute', null=True, verbose_name='Read Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
