# Generated by Django 5.2.4 on 2025-10-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_coinsecuritycheckrequest'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coins',
            field=models.ManyToManyField(blank=True, help_text='Coins related to this post', related_name='posts', to='crypto.cryptocoin'),
        ),
    ]
