# Generated by Django 5.2.4 on 2025-10-02 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_id', models.PositiveIntegerField()),
                ('plan_type', models.CharField(choices=[('ads', 'ads'), ('promotion', 'promotion')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_address', models.CharField(max_length=256)),
                ('token_address', models.CharField(blank=True, max_length=256, null=True)),
                ('token_symbol', models.CharField(blank=True, max_length=64, null=True)),
                ('nonce', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('expired', 'expired')], default='pending', max_length=20)),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
