# Generated by Django 5.2.4 on 2025-10-06 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('tx_hash', None), _negated=True), fields=('tx_hash',), name='unique_nonnull_tx_hash'),
        ),
    ]
