# Generated by Django 5.2.4 on 2025-08-24 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Plan Name')),
                ('duration_in_months', models.PositiveIntegerField(verbose_name='Ad Duration (Months)')),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='ads/banners/', verbose_name='Banner Image')),
                ('wide_banner_image', models.ImageField(upload_to='ads/wide_banners/', verbose_name='Wide Banner Image')),
                ('banner_link', models.URLField(blank=True, null=True, verbose_name='Banner Link')),
                ('wide_banner_link', models.URLField(blank=True, null=True, verbose_name='Wide Banner Link')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('has_payment', models.BooleanField(default=False, verbose_name='Has payment')),
                ('display_ad', models.BooleanField(default=False, verbose_name='Selected for Display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='advertisement.advertisementplan', verbose_name='Advertisement Plan')),
            ],
        ),
    ]
