# Generated by Django 5.2.4 on 2025-10-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementplan',
            name='cost_usd',
        ),
        migrations.AddField(
            model_name='advertisementplan',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cost'),
            preserve_default=False,
        ),
    ]
