# Generated by Django 5.2.4 on 2025-10-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='payment_token_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='recipient_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
