# Generated by Django 5.2.4 on 2025-10-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_siteconfig_payment_token_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('body', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='about_us_image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='about_us',
        ),
    ]
