# Generated by Django 5.2.4 on 2025-10-02 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto', '0007_coinsecuritycheckrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPromotionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Plan Name')),
                ('duration_in_months', models.PositiveIntegerField(verbose_name='Ad Duration (Months)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token Promotion Plan',
                'verbose_name_plural': 'Token Promotion Plans',
            },
        ),
        migrations.CreateModel(
            name='TokenPromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_payment', models.BooleanField(default=False, verbose_name='Has payment')),
                ('is_active', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_promotion_requests', to='crypto.cryptocoin', verbose_name='Top Token')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_promotion_requests', to='promotion.tokenpromotionplan', verbose_name='Token Promotion Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_promotion_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token Promotion Request',
                'verbose_name_plural': 'Token Promotion Requests',
            },
        ),
    ]
