# Generated by Django 5.2.4 on 2025-09-27 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptos', models.CharField(max_length=255)),
                ('exchanges', models.IntegerField()),
                ('market_cap', models.CharField(max_length=255)),
                ('market_cap_percent', models.CharField(max_length=255)),
                ('vol_24h', models.CharField(max_length=255)),
                ('vol_24h_percent', models.CharField(max_length=255)),
                ('dominance', models.CharField(max_length=255)),
                ('fear_and_greed', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoCoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percent_change_1h', models.DecimalField(decimal_places=2, help_text='Change in %', max_digits=6)),
                ('percent_change_24h', models.DecimalField(decimal_places=2, help_text='Change in %', max_digits=6)),
                ('percent_change_7d', models.DecimalField(decimal_places=2, help_text='Change in %', max_digits=6)),
                ('market_cap', models.CharField(max_length=20)),
                ('volume_24h', models.CharField(max_length=20)),
                ('circulating_supply', models.CharField(max_length=30)),
                ('sparkline_in_7d', models.JSONField(blank=True, null=True)),
                ('promoted', models.BooleanField(default=False)),
                ('security_badge', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coins', to='crypto.category')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
