# Generated by Django 5.2.4 on 2025-09-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_category_cryptocoins_promoted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocoins',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptocoins',
            name='sparkline_in_7d',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocoins',
            name='security_badge',
            field=models.BooleanField(default=True),
        ),
    ]
