# Generated by Django 5.2.4 on 2025-09-28 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_alter_cryptocoins_rank_alter_cryptocoins_symbol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coingecko_id', models.CharField(help_text="CoinGecko API ID (e.g. 'bitcoin')", max_length=100, unique=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percent_change_1h', models.DecimalField(decimal_places=2, help_text='Change in %', max_digits=6)),
                ('percent_change_24h', models.DecimalField(decimal_places=2, help_text='Change in %', max_digits=6)),
                ('percent_change_7d', models.DecimalField(decimal_places=2, help_text='Change in %', max_digits=6)),
                ('market_cap', models.CharField(max_length=20)),
                ('volume_24h', models.CharField(max_length=20)),
                ('circulating_supply', models.CharField(max_length=30)),
                ('sparkline_in_7d', models.JSONField(blank=True, null=True)),
                ('promoted', models.BooleanField(default=False)),
                ('security_badge', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coins', to='crypto.category')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='CoinImportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('coingecko', 'CoinGecko'), ('geckoterminal', 'GeckoTerminal')], max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('chain', models.CharField(blank=True, max_length=20, null=True)),
                ('pool_address', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_imports', to=settings.AUTH_USER_MODEL)),
                ('created_coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_requests', to='crypto.cryptocoin')),
            ],
        ),
        migrations.DeleteModel(
            name='CryptoCoins',
        ),
    ]
