# Generated by Django 5.2.4 on 2025-09-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_cryptocoins_last_updated_cryptocoins_sparkline_in_7d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocoins',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=0),
            preserve_default=False,
        ),
    ]
