# Generated by Django 5.2.4 on 2025-09-28 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_cryptocoin_coinimportrequest_delete_cryptocoins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinimportrequest',
            name='source',
        ),
    ]
