# Generated by Django 5.2.4 on 2025-09-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_remove_coinimportrequest_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocoin',
            name='coingecko_id',
            field=models.CharField(max_length=100),
        ),
    ]
