# Generated by Django 5.2.4 on 2025-10-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_coinsecuritycheckrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocoin',
            name='trading_view_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
