# Generated by Django 5.2.4 on 2025-08-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='Symbol')),
                ('promoted', models.BooleanField(default=False, verbose_name='Promoted')),
                ('security_badge', models.BooleanField(default=False, verbose_name='Security Badge')),
                ('trading_view_symbol', models.CharField(max_length=10, verbose_name='TradingView Symbol')),
                ('token_icon', models.ImageField(blank=True, null=True, upload_to='token_icons/', verbose_name='Token Icon')),
                ('about_token', models.TextField(blank=True, null=True, verbose_name='About Token')),
                ('trading_guide_url', models.URLField(blank=True, null=True, verbose_name='Trading Guide URL')),
                ('news_url', models.URLField(blank=True, null=True, verbose_name='News URL')),
                ('telegram_url', models.URLField(blank=True, null=True, verbose_name='Telegram URL')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Website URL')),
                ('token_contract_url', models.URLField(blank=True, null=True, verbose_name='Token Contract URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.CharField(max_length=100, verbose_name='Network')),
                ('pool_address', models.CharField(max_length=256, verbose_name='Pool address')),
                ('base_token', models.CharField(blank=True, max_length=256, null=True, verbose_name='Base Token')),
                ('quote_token', models.CharField(blank=True, max_length=256, null=True, verbose_name='Quote Token')),
            ],
            options={
                'verbose_name': 'Gaming Token',
                'verbose_name_plural': 'Gaming Tokens',
            },
        ),
        migrations.CreateModel(
            name='TopToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='Symbol')),
                ('promoted', models.BooleanField(default=False, verbose_name='Promoted')),
                ('security_badge', models.BooleanField(default=False, verbose_name='Security Badge')),
                ('trading_view_symbol', models.CharField(max_length=10, verbose_name='TradingView Symbol')),
                ('token_icon', models.ImageField(blank=True, null=True, upload_to='token_icons/', verbose_name='Token Icon')),
                ('about_token', models.TextField(blank=True, null=True, verbose_name='About Token')),
                ('trading_guide_url', models.URLField(blank=True, null=True, verbose_name='Trading Guide URL')),
                ('news_url', models.URLField(blank=True, null=True, verbose_name='News URL')),
                ('telegram_url', models.URLField(blank=True, null=True, verbose_name='Telegram URL')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Website URL')),
                ('token_contract_url', models.URLField(blank=True, null=True, verbose_name='Token Contract URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('binance_symbol', models.CharField(max_length=100, unique=True, verbose_name='Binance Symbol')),
                ('token_type', models.CharField(choices=[('TOP_TOKEN', 'Top Token'), ('GAME_RELATED_TOKEN', 'Game Related Token')], max_length=32, verbose_name='Type')),
                ('coingecko_id', models.CharField(max_length=100, unique=True, verbose_name='CoinGecko ID')),
                ('network', models.CharField(blank=True, max_length=100, null=True, verbose_name='Network')),
            ],
            options={
                'verbose_name': 'Top Token',
                'verbose_name_plural': 'Top Tokens',
            },
        ),
    ]
