# Generated by Django 5.2.4 on 2025-08-03 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gaming_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokens.gamingtoken', verbose_name='Gamin Token')),
                ('top_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokens.toptoken', verbose_name='Top Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('top_token__isnull', False)), fields=('top_token',), name='unique_top_token_request'), models.UniqueConstraint(condition=models.Q(('gaming_token__isnull', False)), fields=('gaming_token',), name='unique_gaming_token_request'), models.CheckConstraint(condition=models.Q(models.Q(('gaming_token__isnull', True), ('top_token__isnull', False)), models.Q(('gaming_token__isnull', False), ('top_token__isnull', True)), _connector='OR'), name='exactly_one_token_set')],
            },
        ),
    ]
