# Generated by Django 5.2.4 on 2025-08-11 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0002_tokenupdaterequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamingtoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tokenupdaterequest",
            name="gaming_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token_update_requests",
                to="tokens.gamingtoken",
                verbose_name="Gamin Token",
            ),
        ),
        migrations.AlterField(
            model_name="tokenupdaterequest",
            name="top_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token_update_requests",
                to="tokens.toptoken",
                verbose_name="Top Token",
            ),
        ),
        migrations.AlterField(
            model_name="tokenupdaterequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token_update_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="toptoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
