# Generated by Django 5.2.4 on 2025-08-28 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_alter_tokenupdaterequest_options_tokenlistingrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPromotionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Plan Name')),
                ('duration_in_months', models.PositiveIntegerField(verbose_name='Ad Duration (Months)')),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token Promotion Plan',
                'verbose_name_plural': 'Token Promotion Plans',
            },
        ),
        migrations.CreateModel(
            name='TokenPromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_payment', models.BooleanField(default=False, verbose_name='Has payment')),
                ('expires_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token Promotion Request',
                'verbose_name_plural': 'Token Promotion Requests',
            },
        ),
        migrations.RemoveConstraint(
            model_name='tokenupdaterequest',
            name='unique_top_token_request',
        ),
        migrations.RemoveConstraint(
            model_name='tokenupdaterequest',
            name='unique_gaming_token_request',
        ),
        migrations.RemoveConstraint(
            model_name='tokenupdaterequest',
            name='exactly_one_token_set',
        ),
        migrations.AddConstraint(
            model_name='tokenupdaterequest',
            constraint=models.UniqueConstraint(condition=models.Q(('top_token__isnull', False)), fields=('top_token',), name='unique_top_token_request_in_token_update_request'),
        ),
        migrations.AddConstraint(
            model_name='tokenupdaterequest',
            constraint=models.UniqueConstraint(condition=models.Q(('gaming_token__isnull', False)), fields=('gaming_token',), name='unique_gaming_token_request_in_token_update_request'),
        ),
        migrations.AddConstraint(
            model_name='tokenupdaterequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gaming_token__isnull', True), ('top_token__isnull', False)), models.Q(('gaming_token__isnull', False), ('top_token__isnull', True)), _connector='OR'), name='exactly_one_token_set_in_token_update_request'),
        ),
        migrations.AddField(
            model_name='tokenpromotionrequest',
            name='gaming_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_promotion_requests', to='tokens.gamingtoken', verbose_name='Gamin Token'),
        ),
        migrations.AddField(
            model_name='tokenpromotionrequest',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_promotion_requests', to='tokens.tokenpromotionplan', verbose_name='Token Promotion Plan'),
        ),
        migrations.AddField(
            model_name='tokenpromotionrequest',
            name='top_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_promotion_requests', to='tokens.toptoken', verbose_name='Top Token'),
        ),
        migrations.AddField(
            model_name='tokenpromotionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_promotion_requests', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddConstraint(
            model_name='tokenpromotionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('top_token__isnull', False)), fields=('top_token',), name='unique_top_token_request_in_promotion_request'),
        ),
        migrations.AddConstraint(
            model_name='tokenpromotionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('gaming_token__isnull', False)), fields=('gaming_token',), name='unique_gaming_token_request_in_promotion_request'),
        ),
        migrations.AddConstraint(
            model_name='tokenpromotionrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gaming_token__isnull', True), ('top_token__isnull', False)), models.Q(('gaming_token__isnull', False), ('top_token__isnull', True)), _connector='OR'), name='exactly_one_token_set_in_promotion_request'),
        ),
    ]
