# Generated by Django 5.2.4 on 2025-08-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_tokenpromotionplan_tokenpromotionrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenpromotionrequest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
