# Generated by Django 5.2.4 on 2025-08-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0006_tokenpromotionrequest_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tokenpromotionrequest',
            name='unique_top_token_request_in_promotion_request',
        ),
        migrations.RemoveConstraint(
            model_name='tokenpromotionrequest',
            name='unique_gaming_token_request_in_promotion_request',
        ),
    ]
